/*
 * AddAssetView.java
 *
 * Created on Mar 27, 2010, 4:41:00 PM
 */
package assetl.desktop;

import assetl.system.AssetLControl;
import assetl.system.DataPacket;
import assetl.system.LaptopPacket;

import assetl.system.Asset;

/**
 * Allows an admin to add Assets to the model
 *
 * @author Devin Doman
 */
public class AddAssetView 
   extends AssetView
{
   /**
    * Default constructor expecting controller to add itself.
    */
   public AddAssetView()
   {
      this(null);
   }

   /**
    * Constructor for the user interface
    *
    * @param pControl The controller for this view
    */
   public AddAssetView(AssetLControl pControl)
   {
      super(pControl);
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      mAddBtn = new javax.swing.JButton();
      mBarCodeTxtFld = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      mLaptopNumTxtFld = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      mMakeTxtFld = new javax.swing.JTextField();
      mSerialNumTxtFld = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      mMaintainChkBox = new javax.swing.JCheckBox();
      mLaptopData = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      mAddBtn.setText("Add Asset");
      mAddBtn.setName("mAddBtn"); // NOI18N

      mBarCodeTxtFld.setName("mBarCodeTxtFld"); // NOI18N

      jLabel1.setText("Barcode:");
      jLabel1.setName("jLabel1"); // NOI18N

      mLaptopNumTxtFld.setName("mLaptopNumTxtFld"); // NOI18N

      jLabel2.setText("Laptop Number:");
      jLabel2.setName("jLabel2"); // NOI18N

      jLabel3.setText("Make:");
      jLabel3.setName("jLabel3"); // NOI18N

      mMakeTxtFld.setName("mMakeTxtFld"); // NOI18N

      mSerialNumTxtFld.setName("mSerialNumTxtFld"); // NOI18N

      jLabel4.setText("Serial #:");
      jLabel4.setName("jLabel4"); // NOI18N

      mMaintainChkBox.setText("In Maintenance");
      mMaintainChkBox.setName("mMaintainChkBox"); // NOI18N

      mLaptopData.setName("mLaptopData"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(49, 49, 49)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(mBarCodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel1))
                  .addGap(50, 50, 50)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel2)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mAddBtn)
                        .addComponent(mLaptopNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mMaintainChkBox))
                     .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel3)
                           .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(mMakeTxtFld)
                           .addComponent(mSerialNumTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))))
                  .addGap(85, 85, 85)
                  .addComponent(mLaptopData)))
            .addContainerGap(33, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(layout.createSequentialGroup()
                  .addGap(32, 32, 32)
                  .addComponent(jLabel1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jLabel2)
                  .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(mBarCodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(mLaptopNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(35, 35, 35)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel3)
                     .addComponent(mMakeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(mLaptopData))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(mSerialNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel4))
                  .addGap(18, 18, 18)
                  .addComponent(mMaintainChkBox)
                  .addContainerGap())
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                  .addComponent(mAddBtn)
                  .addGap(63, 63, 63))))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JButton mAddBtn;
   private javax.swing.JTextField mBarCodeTxtFld;
   private javax.swing.JLabel mLaptopData;
   private javax.swing.JTextField mLaptopNumTxtFld;
   private javax.swing.JCheckBox mMaintainChkBox;
   private javax.swing.JTextField mMakeTxtFld;
   private javax.swing.JTextField mSerialNumTxtFld;
   // End of variables declaration//GEN-END:variables

   /**
    * Updates the views display of the model
    */
   public void updateData()
   {
      Asset test = mControl.getAsset(mBarCodeTxtFld.getText());
      mLaptopData.setText(test.getID() + ": " + test.getMake() + " " + test.getType() );
   }

   /**
    * Grabs all pertainent data from the fields and sets them in
    * a DataPacket object. This DataPacket is then returned by the
    * method.
    *
    * @param pFunction The function that needs the DataPacket
    * @return The DataPacket that has been set
    */
   public DataPacket grabDataPacket(String pFunction)
   {
      LaptopPacket laptopPack = new LaptopPacket();

      laptopPack.setBarCode(mBarCodeTxtFld.getText());
      laptopPack.setLaptopNumber(mLaptopNumTxtFld.getText());
      laptopPack.setMake(mMakeTxtFld.getText());
      laptopPack.setSerialNubmer(mSerialNumTxtFld.getText());
      laptopPack.setMaintenance(mMaintainChkBox.isSelected());

      return laptopPack;
   }

   /**
    * Enables functionality passed in for this view.
    */
   public void enable(String pFunction)
   {
      //Enable a FunctionListener for the button
      enable(pFunction, mAddBtn, "Function");
   }

   /**
    * The entry point for this view
    */
   public void run()
   {
      enable("AddAsset");
   }
}
