/*
 * AddPersonView.java
 *
 * Created on Mar 29, 2010, 9:47:33 PM
 */
package assetl.desktop;

import assetl.system.AssetLControl;
import assetl.system.DataPacket;
import assetl.system.PersonPacket;

/**
 * Allows the admin to add Persons to the model
 * 
 * @author Devin Doman
 */
public class AddPersonView
   extends AssetView
{
   /**
    * Default constructor expecting the controller to add itself
    */
   public AddPersonView()
   {
   }

   /**
    * Constructor for the user interface
    *
    * @param pControl The controller for this view
    */
   public AddPersonView(AssetLControl pControl)
   {
      super(pControl);
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
   /**
    * Updates the views display of the model
    */
   public void updateData()
   {
   }

   /**
    * Grabs all pertainent data from the fields and sets them in
    * a DataPacket object. This DataPacket is then returned by the
    * method.
    *
    * @param pFunction The function that needs the DataPacket
    * @return The DataPacket that has been set
    */
   public DataPacket grabDataPacket(String pFunction)
   {
      
      //String pID, String pFirstName, String pMiddleName,
      //String pLastName, String pEmail, String pPhoneNumber

      return new PersonPacket();
   }

   /**
    * Enables functionality passed in for this view.
    */
   public void enable(String pFunction)
   {
   }

   /**
    * The entry point for this view
    */
   public void run()
   {
   }
}
