/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * idView.java
 *
 * Created on Mar 21, 2010, 6:53:41 PM
 */

package assetl.desktop;

import assetl.system.AssetLControl;

/**
 * Prompts for I-number or Laptop number
 *
 * @author Devin Doman
 */
public class IDView
        extends AssetView
{
    /**
     * Default Constructor
     */
    public IDView()
    {
        this(null);
    }

    /** 
     * Creates new form idView 
     */
    public IDView(AssetLControl pControl)
    {
        super(pControl);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Gets the necessary data from the text fields to perform
     * this views functions
     */
    public void grabDataPacket()
    {

    }

    /**
     * Gets any needed data from the model
     */
    public void updateData()
    {
        // There is nothing to update for this view
    }

    /**
     * Enables functionality passed in for this view.
     */
    public void enable(String pFunction)
    {

    }

    /**
     * The entry point for this view
     */
    public void run()
    {
        
    }
}
