package assetl.desktop;

/*
 * ScheduleView.java
 *
 * Created on Mar 14, 2010, 12:44:53 PM
 */



import java.util.Calendar;

import assetl.system.AssetLControl;
import assetl.system.Person;
import assetl.system.Asset;

import assetl.system.DataPacket;
import assetl.system.DBPacket;

/**
 * Provides an interface that can be used to schedule a laptop
 *
 * @author Devin Doman
 */
public class ScheduleView
        extends AssetView
{
    /**
     * Creates a user interface taking a controller
     * as a parameter.
     *
     * @param pControl The controller for this view
     */
    public ScheduleView(AssetLControl pControl)
    {
        super(pControl);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iNumTxtFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dumpData = new javax.swing.JTextArea();
        firstNameTxtFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        laptopNumTxtFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        srtLabel = new javax.swing.JLabel();
        srtMonTxtFld = new javax.swing.JTextField();
        srtDayTxtFld = new javax.swing.JTextField();
        srtYearTxtFld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        endMonTxtFld = new javax.swing.JTextField();
        endDayTxtFld = new javax.swing.JTextField();
        endYearTxtFld = new javax.swing.JTextField();
        scheduleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ScheduleView.class);
        iNumTxtFld.setText(resourceMap.getString("iNumTxtFld.text")); // NOI18N
        iNumTxtFld.setName("iNumTxtFld"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        dumpData.setColumns(20);
        dumpData.setRows(5);
        dumpData.setName("dumpData"); // NOI18N
        jScrollPane1.setViewportView(dumpData);

        firstNameTxtFld.setText(resourceMap.getString("firstNameTxtFld.text")); // NOI18N
        firstNameTxtFld.setName("firstNameTxtFld"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        laptopNumTxtFld.setText(resourceMap.getString("laptopNumTxtFld.text")); // NOI18N
        laptopNumTxtFld.setName("laptopNumTxtFld"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        srtLabel.setText(resourceMap.getString("srtLabel.text")); // NOI18N
        srtLabel.setName("srtLabel"); // NOI18N

        srtMonTxtFld.setText(resourceMap.getString("srtMonTxtFld.text")); // NOI18N
        srtMonTxtFld.setName("srtMonTxtFld"); // NOI18N

        srtDayTxtFld.setText(resourceMap.getString("srtDayTxtFld.text")); // NOI18N
        srtDayTxtFld.setName("srtDayTxtFld"); // NOI18N

        srtYearTxtFld.setText(resourceMap.getString("srtYearTxtFld.text")); // NOI18N
        srtYearTxtFld.setName("srtYearTxtFld"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        endMonTxtFld.setText(resourceMap.getString("endMonTxtFld.text")); // NOI18N
        endMonTxtFld.setName("endMonTxtFld"); // NOI18N

        endDayTxtFld.setText(resourceMap.getString("endDayTxtFld.text")); // NOI18N
        endDayTxtFld.setName("endDayTxtFld"); // NOI18N

        endYearTxtFld.setText(resourceMap.getString("endYearTxtFld.text")); // NOI18N
        endYearTxtFld.setName("endYearTxtFld"); // NOI18N

        scheduleBtn.setText(resourceMap.getString("scheduleBtn.text")); // NOI18N
        scheduleBtn.setName("scheduleBtn"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(iNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(firstNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(srtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(laptopNumTxtFld))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(endMonTxtFld)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(srtMonTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(endDayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(srtDayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(srtYearTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                .addComponent(endYearTxtFld, 0, 0, Short.MAX_VALUE)))
                        .addComponent(scheduleBtn)))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laptopNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srtLabel)
                    .addComponent(srtMonTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srtDayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srtYearTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(endDayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endYearTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endMonTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(scheduleBtn)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dumpData;
    private javax.swing.JTextField endDayTxtFld;
    private javax.swing.JTextField endMonTxtFld;
    private javax.swing.JTextField endYearTxtFld;
    private javax.swing.JTextField firstNameTxtFld;
    private javax.swing.JTextField iNumTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField laptopNumTxtFld;
    private javax.swing.JButton scheduleBtn;
    private javax.swing.JTextField srtDayTxtFld;
    private javax.swing.JLabel srtLabel;
    private javax.swing.JTextField srtMonTxtFld;
    private javax.swing.JTextField srtYearTxtFld;
    // End of variables declaration//GEN-END:variables

    /**
     * Updates the view's display of the model. This function will be
     * called every time the model's state changes.
     */
    public void updateData()
    {
        dumpData.append("Model update.\n The teacher is:" +
                mControl.getPerson(iNumTxtFld.getText()).getFirstName() +
                "\n");
    }

    /**
     * Enables functionality passed in for this view. Gives controller
     * ability to modify this view based on the function being performed
     */
    public void enable(String pFunction)
    {
        // TODO: make sure the function passed in is supported in this view
        // and make the labels of the button and title pretty

        enable(pFunction, scheduleBtn);
        setStart("Schedule".equals(pFunction));
    }

    /**
     * Grabs all pertainent data from the fields and sets them in
     * a DataPacket object. This DataPacket is then returned by the
     * method.
     *
     * @param pFunction The function that needs the DataPacket
     * @return The DataPacket that has been set
     */
    public DataPacket grabDataPacket(String pFunction)
    {
        // TODO: fix this code if we wish to continue using this view for tests

        /*
        //get the person data
        mData.setPerson(new Person(iNumTxtFld.getText()));
        mData.getPerson().setFirstName(firstNameTxtFld.getText());

        //get the laptop data
        mData.setAsset(new Asset(laptopNumTxtFld.getText(), "PC"));

        //make a local calander and set the start and end dates
        Calendar cal = Calendar.getInstance();
        cal.set(Integer.parseInt(srtYearTxtFld.getText()),
                Integer.parseInt(srtMonTxtFld.getText()) + 1,
                Integer.parseInt(srtDayTxtFld.getText()));
        mData.setStart(cal.getTime());
        cal.set(Integer.parseInt(endYearTxtFld.getText()),
                Integer.parseInt(endMonTxtFld.getText()) + 1,
                Integer.parseInt(endDayTxtFld.getText()));
        mData.setEnd(cal.getTime());
         *
         */

        return new DBPacket();
    }

    /**
     * Prepopulates the fields with the data currently held
     * in the member variables or with those in the model.
     */
    @Override
    public void populateFields()
    {
        // TODO: add code to prepopulate the fields when functionality changes
    }

    /**
     * Shows or hides the start date fields.
     *
     * @param pShow If true start date fields are shown
     */
    public void setStart(boolean pShow)
    {
        srtLabel.setVisible(pShow);
        srtYearTxtFld.setVisible(pShow);
        srtMonTxtFld.setVisible(pShow);
        srtDayTxtFld.setVisible(pShow);
    }

    /**
     * Entry point for this view's thread
     */
    public void run()
    {
        //default to schedule ability
        enable("Schedule");
    }
}
