/*
 * AssetView.java
 *
 * Created on Mar 14, 2010, 4:49:04 PM
 */

package assetl.system;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.AbstractButton;


/**
 * An abstract class containing a JMenu
 * common to all view subclasses
 *
 * @author Devin Doman
 */
public abstract class AssetView
        extends JFrame
        implements AssetLView, Runnable
{

    /**
     * The Controller
     */
    protected AssetLControl mControl;

    /**
     * The data packet that can be sent to the controller
     */
    protected DataPacket mPacket;

    /**
     * In place for dynamic class loading. Assumes the controller
     * will immediately be set by the controller that dynamically loaded
     * the view
     */
    public AssetView()
    {
        this(null, "Asset Logger");
    }

    /**
     * Constructor that takes the view's controller as a parameter
     *
     * @param pControl The controller for this view
     */
    public AssetView(AssetLControl pControl)
    {
        this(pControl, "Asset Logger");
    }

    /**
     * Constructor that takes the form's title and controller as parameters
     *
     * @param pControl The controller for this view
     * @param pTitle The title to give the view
     */
    public AssetView(AssetLControl pControl, String pTitle)
    {
        super(pTitle);
        initComponents();
        mControl = pControl;
        mPacket = new DBPacket();

        //
        // add action listeners to the menu items
        //
        
        ckOutMenuItem.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent ev)
            {
                switchFunction("Checkout");
            }
        });

        ckInMenuItem.addActionListener(new ActionListener()
        {
           public void actionPerformed(ActionEvent ev)
           {
               switchFunction("Checkin");
           }
        });

        scheduleMenuItem.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent ev)
            {
                switchFunction("Schedule");
            }
        });

        cancelMenuItem.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent ev)
            {
               switchFunction("Cancel");
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        viewMenu = new javax.swing.JMenu();
        ckOutMenuItem = new javax.swing.JMenuItem();
        ckInMenuItem = new javax.swing.JMenuItem();
        scheduleMenuItem = new javax.swing.JMenuItem();
        cancelMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("File");
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        viewMenu.setText("View");
        viewMenu.setName("viewMenu"); // NOI18N

        ckOutMenuItem.setText("Checkout");
        ckOutMenuItem.setName("ckOutMenuItem"); // NOI18N
        viewMenu.add(ckOutMenuItem);

        ckInMenuItem.setText("Checkin");
        ckInMenuItem.setName("ckInMenuItem"); // NOI18N
        viewMenu.add(ckInMenuItem);

        scheduleMenuItem.setText("Schedule");
        scheduleMenuItem.setName("scheduleMenuItem"); // NOI18N
        viewMenu.add(scheduleMenuItem);

        cancelMenuItem.setText("Cancel");
        cancelMenuItem.setName("cancelMenuItem"); // NOI18N
        viewMenu.add(cancelMenuItem);

        jMenuBar1.add(viewMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cancelMenuItem;
    private javax.swing.JMenuItem ckInMenuItem;
    private javax.swing.JMenuItem ckOutMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem scheduleMenuItem;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables

    /**
     * Allows the controller to set the controller for the view
     */
    public void setControl(AssetLControl pControl)
    {
        mControl = pControl;
    }

    /**
     * Allow the Controller to show the View
     */
    public void showView()
    {
        run();
        setVisible(true);
    }

    /**
     * Allow the Controller to hide the View
     */
    public void hideView()
    {
        setVisible(false);
    }

    /**
     * Allow the Controller to close the View
     */
    public void closeView()
    {
        dispose();
    }

    /**
     * Prepopulates the fields with the data currently held
     * in the member variables or with those in the model.
     * To enable this subclasses must override.
     * @throws UnsupportedOperationException
     */
    public void populateFields()
            throws UnsupportedOperationException
    {
        throw new UnsupportedOperationException("Prepopulate not supported");
    }

    /**
     * Allows the controller to switch to a view that has the functionality
     * provided
     */
    public void switchFunction(String pFunction)
    {
        mControl.setFunction(pFunction);
    }

    /**
     * Enables functionality passed in for this view.
     */
    public abstract void enable(String pFunction);

    /**
     * Removes all event listeners from a button
     *
     * @param pButton The button to remove listeners from
     */
    public void removeButtonListeners(AbstractButton pButton)
    {
        //
        // Get all listeners and then remove each one
        //

        ActionListener[] actions = pButton.getActionListeners();

        for (ActionListener listen : actions)
        {
            pButton.removeActionListener(listen);
        }
   }
}