/*
 * ScheduleView.java
 *
 * Created on Mar 14, 2010, 12:44:53 PM
 */

package assetl.service;

import java.util.Calendar;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import assetl.system.AssetView;
import assetl.system.AssetLControl;
import assetl.system.Person;
import assetl.system.Asset;

/**
 * Provides an interface that can be used to schedule a laptop
 *
 * @author Devin Doman
 */
public class ScheduleView
        extends AssetView
{
    /**
     * Creates a user interface taking a controller
     * as a parameter.
     *
     * @param pControl The controller for this view
     */
    public ScheduleView(AssetLControl pControl)
    {
        super(pControl, "Scheduler");

        initComponents();
        
        //add action listeners
        scheduleBtn.addActionListener(new ScheduleListener());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iNumTxtFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dumpData = new javax.swing.JTextArea();
        firstNameTxtFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        laptopNumTxtFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        srtMonTxtFld = new javax.swing.JTextField();
        srtDayTxtFld = new javax.swing.JTextField();
        srtYearTxtFld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        endMonTxtFld = new javax.swing.JTextField();
        endDayTxtFld = new javax.swing.JTextField();
        endYearTxtFld = new javax.swing.JTextField();
        scheduleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ScheduleView.class);
        iNumTxtFld.setText(resourceMap.getString("iNumTxtFld.text")); // NOI18N
        iNumTxtFld.setName("iNumTxtFld"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        dumpData.setColumns(20);
        dumpData.setRows(5);
        dumpData.setName("dumpData"); // NOI18N
        jScrollPane1.setViewportView(dumpData);

        firstNameTxtFld.setText(resourceMap.getString("firstNameTxtFld.text")); // NOI18N
        firstNameTxtFld.setName("firstNameTxtFld"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        laptopNumTxtFld.setText(resourceMap.getString("laptopNumTxtFld.text")); // NOI18N
        laptopNumTxtFld.setName("laptopNumTxtFld"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        srtMonTxtFld.setText(resourceMap.getString("srtMonTxtFld.text")); // NOI18N
        srtMonTxtFld.setName("srtMonTxtFld"); // NOI18N

        srtDayTxtFld.setText(resourceMap.getString("srtDayTxtFld.text")); // NOI18N
        srtDayTxtFld.setName("srtDayTxtFld"); // NOI18N

        srtYearTxtFld.setText(resourceMap.getString("srtYearTxtFld.text")); // NOI18N
        srtYearTxtFld.setName("srtYearTxtFld"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        endMonTxtFld.setText(resourceMap.getString("endMonTxtFld.text")); // NOI18N
        endMonTxtFld.setName("endMonTxtFld"); // NOI18N

        endDayTxtFld.setText(resourceMap.getString("endDayTxtFld.text")); // NOI18N
        endDayTxtFld.setName("endDayTxtFld"); // NOI18N

        endYearTxtFld.setText(resourceMap.getString("endYearTxtFld.text")); // NOI18N
        endYearTxtFld.setName("endYearTxtFld"); // NOI18N

        scheduleBtn.setText(resourceMap.getString("scheduleBtn.text")); // NOI18N
        scheduleBtn.setName("scheduleBtn"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(iNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(firstNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(laptopNumTxtFld))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(endMonTxtFld, 0, 0, Short.MAX_VALUE)
                                        .addComponent(srtMonTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(endDayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(srtDayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(srtYearTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(endYearTxtFld, 0, 0, Short.MAX_VALUE)))
                            .addComponent(scheduleBtn))
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laptopNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(srtMonTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srtDayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srtYearTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(endMonTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endYearTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(scheduleBtn)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dumpData;
    private javax.swing.JTextField endDayTxtFld;
    private javax.swing.JTextField endMonTxtFld;
    private javax.swing.JTextField endYearTxtFld;
    private javax.swing.JTextField firstNameTxtFld;
    private javax.swing.JTextField iNumTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField laptopNumTxtFld;
    private javax.swing.JButton scheduleBtn;
    private javax.swing.JTextField srtDayTxtFld;
    private javax.swing.JTextField srtMonTxtFld;
    private javax.swing.JTextField srtYearTxtFld;
    // End of variables declaration//GEN-END:variables

    /**
     * Updates the view's display of the model. This function will be
     * called every time the model's state changes.
     */
    public void updateData()
    {
        DatabaseControl myControl = (DatabaseControl) mControl;
        dumpData.append("Model update.\n The teacher is:" +
                myControl.getPerson(iNumTxtFld.getText()).getFirstName() +
                "\n");
    }

    /**
     * Give controller access to modify the current view to enable checkouts
     */
    public void enableCheckout()
    {

    }

    /**
     * This view has no checkin ability, let controller change view
     */
    public void enableCheckin()
    {   
        switchCheckin();
    }

    /**
     * Lets the controller enable checkout function in view if applicable
     */
    public void enableSchedule()
    {

    }

    /**
     * Lets the controller enable checkout function in view if applicable
     */
    public void enableCancel()
    {
        
    }

    /**
     * Gets the data from the text fields and makes objects that can
     * be sent to the controller.
     */
    private void grabData()
    {
        //get the person data
        mPerson = new Person(iNumTxtFld.getText());
        mPerson.setFirstName(firstNameTxtFld.getText());

        //get the laptop data
        mLaptop = new Asset(laptopNumTxtFld.getText(), "PC");

        //make a local calander and set the start and end dates
        Calendar cal = Calendar.getInstance();
        cal.set(Integer.parseInt(srtYearTxtFld.getText()),
                Integer.parseInt(srtMonTxtFld.getText()) + 1,
                Integer.parseInt(srtDayTxtFld.getText()));
        mStart = cal.getTime();
        cal.set(Integer.parseInt(endYearTxtFld.getText()),
                Integer.parseInt(endMonTxtFld.getText()) + 1,
                Integer.parseInt(endDayTxtFld.getText()));
        mEnd = cal.getTime();
    }

    /**
     * Listens for when the user pushed the schedule button. It generates
     * Person, Asset, and Date objects and sends them to the controller
     * to actually schedule a laptop.
     */
    class ScheduleListener
            implements ActionListener
    {
        /**
         * Invoked when the user pushes the schedule button
         *
         * @param ev The event causing this action
         */
        public void actionPerformed(ActionEvent ev)
        {
            grabData();
            mControl.schedule(mPerson, mLaptop, mStart, mEnd);
            System.err.println("User pushed schedule button");
        }
    }

    /**
     * Listens for when the user pushed the checkout button. It generates
     * Person, Asset, and Date objects and sends them to the controller
     * to checkout the laptop.
     */
    class CheckoutListener
            implements ActionListener
    {
        /**
         * Invoked when the user pushes the checkout button
         *
         * @param ev The event causing this action
         */
        public void actionPerformed(ActionEvent ev)
        {
            grabData();
            mControl.checkout(mPerson, mLaptop, mEnd);
            System.err.println("User pushed checkout button");
        }
    }
}
